services:
  frontend:
    build:
      context: ./twitter_trends_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: .
    ports:
      - "5000:5000"
